{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "92289002",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import streamlit as st "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5c636725",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-09-16 09:12:08.502 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.803 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\user\\AppData\\Roaming\\Python\\Python314\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-09-16 09:12:08.804 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.810 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.828 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.828 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.842 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.844 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.845 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.845 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.846 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.847 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.850 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-16 09:12:08.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"\n",
    "streamlit에서 텍스트를 사용하는 방법\n",
    "\n",
    "title()\n",
    "subtitle()\n",
    "header()\n",
    "write()\n",
    "text()\n",
    "code()\n",
    "markdown()\n",
    "\n",
    "\"\"\"\n",
    "import streamlit as st\n",
    "\n",
    "# streamlit run <실행하고자 하는 파이썬 파일>\n",
    "\n",
    "# 가장 큰 제목\n",
    "# st.title('온라인 쇼핑몰 매출 분석')\n",
    "# # 주요 영역 제목\n",
    "# st.header('2026년 매출 현황')\n",
    "# # 세부 영역 제목\n",
    "# st.subheader('8월 매출')\n",
    "# # 일반적인 내용\n",
    "# st.write('8월 매출 데이터를 분석합니다.')\n",
    "\n",
    "price = 1000\n",
    "amount = 5\n",
    "\n",
    "st.write(f'총 가격은 {price * amount}원입니다')\n",
    "\n",
    "st.title('쇼핑몰 운영 대시보드')\n",
    "st.header('매출 현황')\n",
    "st.subheader('금일 매출 현황')\n",
    "st.write('오늘 발생한 주문의 매출을 확인합니다.')\n",
    "st.subheader('월간 매출')\n",
    "st.write('이번달 누적 매출을 확인합니다.')\n",
    "st.header('고객 현황')\n",
    "st.subheader('신규 가입자')\n",
    "st.write('오늘 가입한 신규 고객을 확인합니다.')\n",
    "\n",
    "st.title('이것은 title이구요')\n",
    "st.write('**판매량** : 120개')\n",
    "st.text('**매출액** : 3500000')\n",
    "\n",
    "st.caption('매출 데이터는 매일 오전 9시에 갱신됩니다.')\n",
    "st.caption('기준일: 2026-09-15')\n",
    "st.caption('단위: 1TEU')\n",
    "\n",
    "\n",
    "st.markdown(\n",
    "    \"이번달 매출은 **무려** **35000000** 이며\"\n",
    "    \"*전월보다 많이 증가했습니다 :)*\"\n",
    ")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "### 매출 분석 결과\n",
    "\n",
    "이번 달 주요 지표입니다.\n",
    "\n",
    "- 총 주문수: 30건\n",
    "- 총 매출: 10만원\n",
    "- 평균 주문 금액: 3만원\n",
    "\n",
    "매출은 지난달보다 32.5%증가했습니다.\n",
    "\"\"\")\n",
    "\n",
    "st.code(\n",
    "    \"\"\"\n",
    "    \"\"\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cad37a1b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
